[theme]
base="light"

[server]
maxUploadSize = 1

# Primary accent for interactive elements
primaryColor = '#799BE6'

# Background color for the main content area
#backgroundColor = '#fdfdfd'

# Background color for sidebar and most interactive widgets
#secondaryBackgroundColor = '#FFFFFF' #'#799BE688'

# Color used for almost all text
#textColor = '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"

[deprecation]
showPyplotGlobalUse = false